### ISSUE TITLE
Unable to affect speed

### ISSUE THREAD

**Issue by HZSamir** [benjamineruvieru/react-native-type-animation#2]
Hello, and thank you for this library.

I'm having trouble adjusting the speed of typing and deletion. I've tried every prop but the speed refuses to change.
What am I doing wrong?

` <TypeAnimation
            blinkSpeed={10}
            sequence={[
              {
                text: "One",
                typeSpeed: 1,
                delayBetweenSequence: 1,
                deletionSpeed: 1,
              },
              {
                text: "One Two Three",
                typeSpeed: 1,
                delayBetweenSequence: 1,
                deletionSpeed: 1,
              },
            ]}
            loop
            delayBetweenSequence={10}
          />`

**Comment by benjamineruvieru** [comment]
Hi there, I tested now and this doesn't seem to be a problem for me, I copied the example you dropped and it worked perfectly.
 

https://github.com/benjamineruvieru/react-native-type-animation/assets/101414331/0cadd59a-5b24-4ef3-a5b1-3bae8a6149b4

Please try again and let me know if you are still facing any issue

**Comment by HZSamir** [comment]
@benjamineruvieru It turns out the typing speed gets slow if you have debugging enabled.
Thank you for taking the time, and for this very helpful library.
Cheers!
